version: '3.8'

services:
  app:
    # TODO: Use volume to store generated secret key?
    build:
      context: ..
      dockerfile: docker/app/app.Dockerfile
    restart: always
    env_file:
      - ".env"
    environment:
      DATABASE_URI: "mysql://flask:BADPASSWD@db:3306/bingodb"
    ports:
      - "8080:80"
    networks:
      - server
      - backend
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: flask
      MYSQL_PASSWORD: BADPASSWD
      MYSQL_DATABASE: bingodb
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10


# TODO: Use volumes to allow db persistence

networks:
  server:  # Outward facing, makes a bridge for hosting the webapp
    driver: bridge
  backend: # Internal; just for the app to communicate with the db
    driver: bridge
    internal: true
